name: Bug Report
description: Report a bug or crash you believe is caused by Nightfall
body:
  - type: input
    id: mod-version
    attributes:
      label: Nightfall version
      description: |
        Identified in main menu under mods or jar file name
      placeholder: "1.0.0b"
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge version
      placeholder: "40.3.0"
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Custom modpack info
      description: |
        Name and version of modpack (if using a private pack, list all mods in issue description)
      placeholder: "Nightfall: Definitive Edition - 1.0.0b"
    validations:
        required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe what happened in as much detail as possible.
        State what game behavior you expected to occur and why you believe the resulting behavior is a bug.
        Screenshots and videos are encouraged when applicable.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce if possible
      placeholder: |
        1. First step
        2. Second step...
  - type: textarea
    id: log-file
    attributes:
      label: "Log file"
      description: "The associated log file in your .minecraft/logs. If you just played, this will be latest.log"
      placeholder: "Attach your log file here"
    validations:
      required: true